// TODO: allow mapping a command over each file

/// `relativePosix` only understands `/` separators; Zig passes Windows paths with `\`.
fn dupePosixPathSegments(allocator: std.mem.Allocator, path: []const u8) ![]const u8 {
    const dup = try allocator.dupe(u8, path);
    if (std.fs.path.sep != '/') {
        _ = std.mem.replace(u8, dup, "\\", "/");
    }
    return dup;
}

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const cwd = std.Io.Dir.cwd();

    var args_iter = try std.process.Args.Iterator.initAllocator(init.minimal.args, gpa);
    defer args_iter.deinit();
    _ = args_iter.next();
    const input_path = args_iter.next() orelse usage("missing input path");
    const output_dir_path = args_iter.next() orelse usage("missing input path prefix");
    const index_file_path = args_iter.next() orelse usage("missing output path");
    const options_json = args_iter.next() orelse usage("missing options");
    if (args_iter.next() != null) usage("too many arguments");

    const options_parsed = try std.json.parseFromSlice(Options, gpa, options_json, .{});
    defer options_parsed.deinit();
    const opts = options_parsed.value;

    const Entry = struct {
        path: []const u8,
        children: usize,
        depth: usize,
    };
    var entries: std.ArrayList(Entry) = .empty;
    var entry_arena: std.heap.ArenaAllocator = .init(gpa);
    defer {
        entries.deinit(gpa);
        entry_arena.deinit();
    }

    {
        const Frame = struct {
            iter: std.Io.Dir.Iterator,
            out: std.Io.Dir,
            entry: usize,

            pub fn deinit(frame: *@This(), close_io: std.Io) void {
                frame.iter.reader.dir.close(close_io);
                frame.out.close(close_io);
            }
        };
        var stack: std.ArrayList(Frame) = .empty;
        defer {
            for (stack.items) |*frame| frame.deinit(io);
            stack.deinit(gpa);
        }

        {
            var in = cwd.openDir(io, input_path, .{ .iterate = true }) catch |err| {
                std.log.err("unable to open input directory '{s}'", .{input_path});
                return err;
            };
            errdefer in.close(io);

            var out = cwd.openDir(io, output_dir_path, .{}) catch |err| {
                std.log.err("unable to open output directory '{s}'", .{output_dir_path});
                return err;
            };
            errdefer out.close(io);

            try stack.append(gpa, .{
                .iter = in.iterateAssumeFirstIteration(),
                .out = out,
                .entry = entries.items.len,
            });
            try entries.append(gpa, .{ .path = "", .depth = 0, .children = 0 });
        }

        while (stack.items.len > 0) {
            const frame = &stack.items[stack.items.len - 1];
            const entry = try frame.iter.next(io) orelse {
                frame.deinit(io);
                stack.items.len -= 1;
                continue;
            };

            const parent = &entries.items[frame.entry];
            parent.children += 1;
            const path = try std.mem.concat(entry_arena.allocator(), u8, &.{
                parent.path,
                entry.name,
                if (entry.kind == .directory) "/" else "",
            });
            try entries.append(gpa, .{
                .path = path,
                .depth = stack.items.len - 1,
                .children = 0,
            });

            if (entry.kind == .directory) {
                var in = try frame.iter.reader.dir.openDir(io, entry.name, .{ .iterate = true });
                errdefer in.close(io);

                var out = try frame.out.createDirPathOpen(io, entry.name, .{});
                errdefer out.close(io);

                try stack.append(gpa, .{
                    .iter = in.iterateAssumeFirstIteration(),
                    .out = out,
                    .entry = entries.items.len - 1,
                });
            } else {
                try frame.iter.reader.dir.copyFile(entry.name, frame.out, entry.name, io, .{});
            }
        }
    }

    var source_data: std.Io.Writer.Allocating = .init(gpa);
    defer source_data.deinit();
    const source = &source_data.writer;

    try source.writeAll("// This file was autogenerated by assetpack\n");

    if (opts.asset_namespace) |ns| {
        try source.print(fmt.pub_const ++ " = struct {{", .{
            std.zig.fmtId(ns),
        });
    }

    {
        std.mem.sortUnstable(Entry, entries.items, {}, struct {
            fn less(_: void, a: Entry, b: Entry) bool {
                const a_is_dir = std.mem.endsWith(u8, a.path, "/");
                const b_is_dir = std.mem.endsWith(u8, b.path, "/");
                if (a_is_dir == b_is_dir) {
                    return std.mem.lessThan(u8, a.path, b.path);
                } else {
                    return b_is_dir;
                }
            }
        }.less);

        const index_dir = std.fs.path.dirname(index_file_path) orelse ".";
        const index_dir_posix = try dupePosixPathSegments(gpa, index_dir);
        defer gpa.free(index_dir_posix);
        const output_dir_posix = try dupePosixPathSegments(gpa, output_dir_path);
        defer gpa.free(output_dir_posix);

        const path_prefix = try std.fs.path.relativePosix(
            gpa,
            ".",
            index_dir_posix,
            output_dir_posix,
        );
        defer gpa.free(path_prefix);

        if (std.mem.startsWith(u8, path_prefix, "../")) {
            std.log.err("output directory not a subdirectory of output module root", .{});
            return error.InvalidOutputDirectory;
        }
        std.debug.assert(std.mem.indexOf(u8, path_prefix, "/../") == null);

        var prev_path: []const u8 = "";
        std.debug.assert(entries.items[0].path.len == 0);
        for (entries.items[1..]) |entry| {
            if (std.mem.endsWith(u8, entry.path, "/")) break;

            const byte_diff = std.mem.indexOfDiff(u8, entry.path, prev_path).?;
            const diff = if (entry.path[byte_diff] == '/')
                byte_diff
            else if (std.mem.lastIndexOfScalar(u8, entry.path[0..byte_diff], '/')) |sep|
                sep + 1
            else
                0;

            for (0..std.mem.count(u8, prev_path[diff..], "/")) |_| {
                try source.writeAll("};");
            }

            var pos = diff;
            while (std.mem.indexOfScalarPos(u8, entry.path, pos, '/')) |sep| : (pos = sep + 1) {
                try source.print(fmt.pub_const ++ " = struct {{", .{
                    std.zig.fmtId(entry.path[pos..sep]),
                });
            }

            try source.print(fmt.pub_const ++ " = " ++ fmt.embedfile, .{
                std.zig.fmtId(entry.path[pos..]),
                fmt.zigString(path_prefix),
                fmt.zigString(entry.path),
            });

            prev_path = entry.path;
        }

        for (0..std.mem.count(u8, prev_path, "/")) |_| {
            try source.writeAll("};");
        }
    }

    if (opts.asset_namespace != null) {
        try source.writeAll("};");
    }

    const asset_namespace = if (opts.asset_namespace) |ns|
        try std.fmt.allocPrint(gpa, fmt.f, .{std.zig.fmtId(ns)})
    else
        try gpa.dupe(u8, "@This()");
    defer gpa.free(asset_namespace);

    if (opts.root_dir_decl) |ns| {
        std.mem.sort(Entry, entries.items, {}, struct {
            fn less(_: void, a: Entry, b: Entry) bool {
                if (a.depth != b.depth) return a.depth < b.depth;
                return std.mem.lessThan(u8, a.path, b.path);
            }
        }.less);

        std.debug.assert(entries.items[0].path.len == 0);
        try source.print(
            fmt.pub_const ++
                \\: @import("assetpack").Dir = .{{
                \\.offset = 0,
                \\.children = {},
                \\.map = .{{ .entries = &.{{
            ,
            .{ std.zig.fmtId(ns), entries.items[0].children },
        );

        var start: usize = entries.items[0].children;
        for (entries.items[1..]) |entry| {
            const name = std.fs.path.basenamePosix(entry.path);
            if (entry.path.len == 0 or std.mem.endsWith(u8, entry.path, "/")) {
                try source.print("\n.dir(\"" ++ fmt.f ++ "\", {}, {}),", .{
                    fmt.zigString(name),
                    start,
                    entry.children,
                });
                start += entry.children;
            } else {
                try source.print("\n.file(\"" ++ fmt.f ++ "\", {s}", .{
                    fmt.zigString(name),
                    asset_namespace,
                });
                var it = std.mem.splitScalar(u8, entry.path, '/');
                while (it.next()) |el| {
                    try source.print("." ++ fmt.f, .{std.zig.fmtId(el)});
                }
                try source.writeAll("),");
            }
        }
        try source.writeAll("\n} }, };");
    }

    if (opts.expose_types) {
        try source.writeAll(
            \\
            \\pub const Dir = @import("assetpack").Dir;
            \\
        );
    }

    const source_slice = try source_data.toOwnedSliceSentinel(0);
    defer gpa.free(source_slice);
    var ast: std.zig.Ast = try .parse(gpa, source_slice, .zig);
    defer ast.deinit(gpa);

    if (ast.errors.len > 0) {
        try std.zig.printAstErrorsToStderr(gpa, io, ast, "<generated>", .auto);
        var lines = std.mem.splitScalar(u8, source_slice, '\n');
        var line_num: usize = 1;
        while (lines.next()) |line| : (line_num += 1) {
            std.debug.print("{: >4}: {s}\n", .{ line_num, line });
        }
        std.debug.print("\n", .{});
        std.process.fatal("Generated invalid code. This is a bug in assetpack.", .{});
    }

    var out_file = try cwd.createFile(io, index_file_path, .{});
    defer out_file.close(io);
    var out_buf: [4096]u8 = undefined;
    var out = out_file.writer(io, &out_buf);
    try ast.render(gpa, &out.interface, .{});
    try out.interface.flush();
}

fn usage(err_msg: []const u8) noreturn {
    std.debug.print("Usage: assetpack INPUT_DIR OUTPUT_DIR OUTPUT_ZIG_FILE OPTIONS_JSON", .{});
    std.log.err("{s}", .{err_msg});
    std.process.exit(1);
}

const fmt = struct {
    const f = "{f}";
    const pub_const = "\npub const " ++ f;
    const embedfile = "@embedFile(\"" ++ f ++ "/" ++ f ++ "\");";
    const zigString = std.zig.fmtString;
};

const std = @import("std");
const Options = @import("Options.zig");
